<?php

declare(strict_types=1);

namespace App\Enum;

enum QuestCategory: string
{
    case GOLD_SPENT = 'GOLD_SPENT';
    case LEVEL_UP = 'LEVEL_UP';
    case FIGHTS_WON = 'FIGHTS_WON';
    case FIGHTS_LOST = 'FIGHTS_LOST';
    case ITEMS_COLLECTED = 'ITEMS_COLLECTED';
    case RARE_ITEM_COLLECTED = 'RARE_ITEM_COLLECTED';
    case EQUIPMENT_FULL = 'EQUIPMENT_FULL';
    case RARE_EQUIPMENT_FULL = 'RARE_EQUIPMENT_FULL';
    case ALL_DUNGEONS_COMPLETED = 'ALL_DUNGEONS_COMPLETED';
    case ALL_DUNGEONS_AND_LEVEL = 'ALL_DUNGEONS_AND_LEVEL';
    case LEGENDARY_ITEM_COLLECTED = 'LEGENDARY_ITEM_COLLECTED';
    case DUNGEON_COMPLETED = 'DUNGEON_COMPLETED';
    case BESTIARY_ENTRIES_DISCOVERED = 'BESTIARY_ENTRIES_DISCOVERED';
    case EPIC_ITEM_COLLECTED = 'EPIC_ITEM_COLLECTED';
    case EPIC_EQUIPMENT_FULL = 'EPIC_EQUIPMENT_FULL';
    case LEGENDARY_EQUIPMENT_FULL = 'LEGENDARY_EQUIPMENT_FULL';
    case ALL_DUNGEON_TITLES_UNLOCKED = 'ALL_DUNGEON_TITLES_UNLOCKED';
    case ALL_TITLES_UNLOCKED = 'ALL_TITLES_UNLOCKED';
    case QUEST_LINE_COMPLETED = 'QUEST_LINE_COMPLETED';
}
