<?php

declare(strict_types=1);

namespace App\Enum;

enum TitleUnlockType: string
{
    case GAME_START = 'GAME_START';
    case LEVEL_REACHED = 'LEVEL_REACHED';
    case GOLD_BALANCE = 'GOLD_BALANCE';
    case DUNGEON_COMPLETED = 'DUNGEON_COMPLETED';
    case ITEMS_COLLECTED = 'ITEMS_COLLECTED';
    case RARE_EQUIPMENT_FULL = 'RARE_EQUIPMENT_FULL';
    case ALL_DUNGEONS_COMPLETED = 'ALL_DUNGEONS_COMPLETED';
    case ALL_DUNGEONS_AND_LEVEL = 'ALL_DUNGEONS_AND_LEVEL';
    case LEGENDARY_ITEMS_COLLECTED = 'LEGENDARY_ITEMS_COLLECTED';
    case FIGHTS_WON = 'FIGHTS_WON';
    case BESTIARY_COMPLETE = 'BESTIARY_COMPLETE';
    case EPIC_ITEMS_COLLECTED = 'EPIC_ITEMS_COLLECTED';
    case EPIC_EQUIPMENT_FULL = 'EPIC_EQUIPMENT_FULL';
    case LEGENDARY_EQUIPMENT_FULL = 'LEGENDARY_EQUIPMENT_FULL';
}
